social_auth_gitlab.settings:
  type: config_object
  label: 'Social Auth GitLab settings'
  mapping:
    client_id:
      type: string
      label: 'Client ID'
    client_secret:
      type: string
      label: 'Client Secret'
    endpoints:
      type: string
      label: 'API Endpoints to be requested'
